@echo off
echo 🚀 Iniciando Visor de Difusión...
echo 📁 Cambiando a directorio frontend...
cd frontend
echo 📦 Instalando dependencias (si es necesario)...
call npm install
echo 🌐 Iniciando servidor de desarrollo...
call npm run dev